//basically stl in cpp is mainly into four imp parts
// CONTAINERS
// ITERATORS
// ALGORITHMS
// FUNCTORS

// C O N T A I N E R S
// containers are pre implemented data structures written in stl, there are more
//containers in stl however i only wrote those which are imp for CP

// S E Q U E N T I A L   C O N T A I N E R S
//just like arrays which implements sequentially
// vectors, stacks, queue, pair(not a container, it is rather a class , just i wrote it here)

// O R D E R E D
// static_assert those in which values are stored in sorted order
// maps, multimap, set, multiset

// U N O R D E R E D
// based on hashing algorithms, in which values are hashed and stores things
// unordered map, unordered set

// N E S T E D   C O N T A I N E R 
// LIKE
// vector< vector <int>>
// map<int, vector <int>>
// set<pair<int, string>>
// vector<map<int, set<int>>>